apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: frontend
    component: frontend
    version: green
spec:
  replicas: 4
  selector:
    # by using these lables replica set select the pod
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
      version: green
  # this is pod , as we know pod is the subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: frontend
        component: frontend
        version: green
    spec:
      containers:
      - name: nginx-green
        image: esrasd/blue-green:0.0.2
